version: 2

build:
  image: latest
  os: "ubuntu-22.04"
  tools:
    python: 3.12

python:
  install:
    - method: pip
      path: .
      # extra_requirements:
      #   - docs

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - pdf
  - epub
